version: "3.7"

networks:
  paris_to_berlin_net:

services:

  from-paris-to-berlin-service:
    hostname: from-paris-to-berlin-service
    container_name: from-paris-to-berlin-service
    build:
      context: from-paris-to-berlin-resilience4j-aop-spring-app/.
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      retries: 30
    environment:
      - FPTB_BACK_END_WS_WEB_IP=from-paris-to-berlin-ws-service
    networks:
      paris_to_berlin_net:

  from-paris-to-berlin-ws-service:
    hostname: from-paris-to-berlin-ws-service
    container_name: from-paris-to-berlin-ws-service
    build:
      context: from-paris-to-berlin-ws-service/.
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/8081' || exit 1
      interval: 10s
      retries: 30
    networks:
      paris_to_berlin_net:

  from-paris-to-berlin-fe:
    hostname: from-paris-to-berlin-fe
    container_name: from-paris-to-berlin-fe
    build:
      context: from-paris-to-berlin-web/.
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 10s
      retries: 30
    env_file:
      - .env
    networks:
      paris_to_berlin_net:
    depends_on:
      from-paris-to-berlin-service:
        condition: service_started
      from-paris-to-berlin-ws-service:
        condition: service_started
