version: "3.7"

networks:
  paris_to_berlin_net:

services:

  from-paris-to-berlin-service:
    ports:
      - "8080:8080"

  from-paris-to-berlin-ws-service:
    ports:
      - "8081:8081"

  from-paris-to-berlin-fe:
    ports:
      - "9000:9000"
