version: "3.7"

networks:
  paris_to_berlin_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:

  from_paris_to_berlin_web:
    ports:
      - "8080:8080"

  from_paris_to_berlin_fe:
    ports:
      - "9000:9000"
