server:
  servlet.context-path: /api/fptb
  port: 8081

hazelcast:
  serialization:
    serializers:
      - type-class: Location
        class-name: LocationStreamSerializer
      - type-class: Car
        class-name: CarStreamSerializer
      - type-class: RoadBlockTime
        class-name: RoadBlockTimeStreamSerializer
spring:
  main:
    web-application-type: servlet
fptb:
  server:
    url: "http://localhost:${server.port}"