name: PR from-paris-to-berlin-circuit-breaker-pull_request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Maven Build and Test
      run:  mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Node.js Build and Test
      run: cd from-paris-to-berlin-web && yarn install && npm run build
