name: PR from-paris-to-berlin-circuit-breaker-pull_request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Maven Build and Test
      uses: nick-fields/retry@v2
      with:
        max_attempts: 3
        retry_on: error
        timeout_seconds: 2400
        command: |
          mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Node.js Build and Test
      run: cd from-paris-to-berlin-web && yarn install && npm run build
