name: PR from-paris-to-berlin-circuit-breaker-pull_request


on:
  create:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Maven Build and Test
      uses: nick-fields/retry@v3
      with:
        max_attempts: 3
        retry_on: error
        timeout_seconds: 2400
        command: |
          mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Node.js Build and Test
      run: cd from-paris-to-berlin-web && yarn install && npm run build
