name: E2E from-paris-to-berlin-circuit-breaker

on:
  push:
    branches: [ main ]

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Locust
        run: sudo pip3 install locust

      - name: Start Docker
        run: make dcup-full-action
      - name: Start Locust
        run: make locust
      - name: Run Cypress
        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Locust
        run: sudo pip3 install locust

      - name: Start Docker
        run: make dcup-full-action
      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Locust
        run: sudo pip3 install locust

      - name: Start Docker
        run: make dcup-full-action
      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-firefox


  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Locust
        run: sudo pip3 install locust

      - name: Start Docker
        run: make dcup-full-action
      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-edge

